#Colors in RGB
[[orders]]
name = "Red"
difficulty = 0
sections = [{ color = [255, 0.0, 0.0], size = 30 }]

[[orders]]
name = "Blue"
difficulty = 0
sections = [{ color = [0.0, 34.0, 255.0], size = 30 }]

[[orders]]
name = "Yellow"
difficulty = 0
sections = [{ color = [234.0, 255.0, 0.0], size = 30 }]

[[orders]]
name = "Red - Yellow"
difficulty = 1
sections = [
    { color = [255, 0.0, 0.0], size = 15 },
    { color = [234.0, 255.0, 0.0], size = 15 },
]

[[orders]]
name = "Blue - Red"
difficulty = 1
sections = [
    { color = [0.0, 34.0, 255.0], size = 15 },
    { color = [255, 0.0, 0.0], size = 15 },
]

[[orders]]
name = "Yellow - Blue"
difficulty = 1
sections = [
    { color = [234.0, 255.0, 0.0], size = 15 },
    { color = [0.0, 34.0, 255.0], size = 15 },
]
